<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<RootNamespace>CodeMe.ServiceErrors</RootNamespace>
		<LangVersion>latest</LangVersion>

		<Description>Library for typed service errors (Problem Details-alike DTOs)</Description>
		<PackageTags>errors;typed errors</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PolySharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>